# Generated by Django 2.2.6 on 2019-10-27 12:33

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_content_excerpt',
            field=models.TextField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=model_utils.fields.SplitField(no_excerpt_field=True),
        ),
    ]
