# Generated by Django 2.2.6 on 2019-10-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191027_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_content_excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
